### ISSUE TITLE
[SkullUtils] - Load failure on Paper `testing/no-relocation`

### ISSUE THREAD

**Issue by datatags** [CryptoMorin/XSeries#240]
**Description**
When using this in my plugin on the Paper `testing/no-relocation` branch, SkullUtils returns an error:
```
Error occurred while enabling UltraCosmetics v3.4.2 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at be.isach.ultracosmetics.shaded.xseries.SkullUtils.<clinit>(SkullUtils.java:83) ~[?:?]
        at be.isach.ultracosmetics.util.ItemFactory.createSkull(ItemFactory.java:196) ~[?:?]
        at be.isach.ultracosmetics.cosmetics.type.HatType.<init>(HatType.java:36) ~[?:?]
        at be.isach.ultracosmetics.cosmetics.type.HatType.register(HatType.java:79) ~[?:?]
        at be.isach.ultracosmetics.cosmetics.type.CosmeticType.registerAll(CosmeticType.java:99) ~[?:?]
        at be.isach.ultracosmetics.UltraCosmetics.start(UltraCosmetics.java:313) ~[?:?]
        at be.isach.ultracosmetics.UltraCosmetics.onEnable(UltraCosmetics.java:215) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.4.jar:git-Paper-"01730f6"
]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-"01730f6"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:637) ~[paper-1.20.4.jar:git-Paper-"01730f6"]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:548) ~[paper-1.20.4.jar:git-Paper-"01730f6"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-"01730f6"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-"01730f6"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.4.jar:git-Paper-"01730f6"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-"01730f6"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-"01730f6"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Failed to parse server version. Could not find any package starting with name: 'org.bukkit.craftbukkit.v'
        at be.isach.ultracosmetics.shaded.xseries.ReflectionUtils.<clinit>(ReflectionUtils.java:95) ~[?:?]
        ... 19 more
```

**Version**
Paper 1.20.4, `testing/no-relocation` branch: https://github.com/PaperMC/testing/releases/tag/no-relocation
XSeries 9.8.1

**Additional Information**
https://forums.papermc.io/threads/paper-velocity-1-20-4.998/#post-2955
https://github.com/datatags/UltraCosmetics/issues/153

**Comment by CryptoMorin** [comment]
Fixed in v10.0.0
