### ISSUE TITLE
[XItemStack] - NETHER_PORTAL is no longer an item in 1.21

### ISSUE THREAD

**Issue by HSGamer** [CryptoMorin/XSeries#275]
**Description**
```
java.lang.IllegalArgumentException: NETHER_PORTAL isn't an item
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.inventory.ItemStack.of(ItemStack.java:58) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:138) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:117) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:104) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:87) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at ModularMob-1.0-SNAPSHOT.jar/me.hsgamer.modularmob.lib.xseries.XItemStack.deserialize(XItemStack.java:453) ~[ModularMob-1.0-SNAPSHOT.jar:?]
        at ModularMob-1.0-SNAPSHOT.jar/me.hsgamer.modularmob.lib.xseries.XItemStack.deserialize(XItemStack.java:466) ~[ModularMob-1.0-SNAPSHOT.jar:?]
        at java.base/java.util.Optional.map(Optional.java:260) ~[?:?]
```

When deserializing the item config in 1.21, the `DEFAULT_MATERIAL` in XItemStack uses `NETHER_PORTAL` as a default itemstack, which is illegal by Spigot.

I guess we need to change the default material to something else.

**Version**
1.21

**Comment by HSGamer** [comment]
This affects `XEntity` so we definitely need to change the default material
