### ISSUE TITLE
[XMaterial] - NoClassDefFoundError: me/activated/core/shade/apache/commons/lang/WordUtils

### ISSUE THREAD

**Issue by Boryte** [CryptoMorin/XSeries#293]
**Description**
Hey CryptoMarin, I'm using your library in my plugin I hope that's ok with you and some of my customers are getting this issue in 1.8.8. Have you changed something internally?

[code][SGReborn] Enabling SGReborn v1.6
[13:08:09 ERROR]: Error occurred while enabling SGReborn v1.6 (Is it up to date?)
java.lang.NoClassDefFoundError: me/activated/core/shade/apache/commons/lang/WordUtils
        at com.cryptomorin.xseries.XMaterial.toString(XMaterial.java:2059) ~[?:?]
        at sgreborn.manager.ItemManager.itemToString(ItemManager.java:396) ~[?:?]
        at sgreborn.util.config.Config.<clinit>(Config.java:298) ~[?:?]
        at sgreborn.manager.ConfigManager.createConfig(ConfigManager.java:116) ~[?:?]
        at sgreborn.SGReborn.onEnable(SGReborn.java:106) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.ClassNotFoundException: me.activated.core.shade.apache.commons.lang.WordUtils
        at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-21fe707-741a1bd]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 16 more[/code]

**Version**
1.8.8

**Comment by CryptoMorin** [comment]
Did you see my reply on Spigot?
