### ISSUE TITLE
[XSound] - 1.21.3 Support Issue

### ISSUE THREAD

**Issue by ImYenil** [CryptoMorin/XSeries#310]
[14:38:49 ERROR]: [DeliveryMan] Error initializing plugin 'DeliveryMan-1.2.1.jar' in folder 'plugins\.paper-remapped' (Is it up to date?)
java.lang.IllegalStateException: Unable to load DeliveryMan
        at DeliveryMan-1.2.1.jar/deliveryman.bootstrap.DeliveryManPlugin.onLoad(DeliveryManPlugin.java:57) ~[DeliveryMan-1.2.1.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.21.3.jar:1.21.3-27-661839e]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.21.3.jar:1.21.3-27-661839e]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.21.3.jar:1.21.3-27-661839e]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[paper-1.21.3.jar:1.21.3-27-661839e]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:549) ~[paper-1.21.3.jar:1.21.3-27-661839e]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:289) ~[paper-1.21.3.jar:1.21.3-27-661839e]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[paper-1.21.3.jar:1.21.3-27-661839e]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:339) ~[paper-1.21.3.jar:1.21.3-27-661839e]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.RuntimeException: Failed to invoke constructor 'deliveryman.reward.RewardSounds()' with no args
        at com.google.gson.internal.ConstructorConstructor$9.construct(ConstructorConstructor.java:274) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.createAccumulator(ReflectiveTypeAdapterFactory.java:427) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:383) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:186) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:144) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1329) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1300) ~[gson-2.10.1.jar:?]
        at DeliveryMan-1.2.1.jar/deliveryman.config.MappedConfiguration.getAs(MappedConfiguration.kt:93) ~[DeliveryMan-1.2.1.jar:?]
        at DeliveryMan-1.2.1.jar/deliveryman.config.PluginSettings.<init>(PluginSettings.kt:10) ~[DeliveryMan-1.2.1.jar:?]
        at DeliveryMan-1.2.1.jar/deliveryman.config.PluginSettings.<init>(PluginSettings.kt) ~[DeliveryMan-1.2.1.jar:?]
        at DeliveryMan-1.2.1.jar/deliveryman.config.PluginSettings$Companion.reload(PluginSettings.kt:22) ~[DeliveryMan-1.2.1.jar:?]
        at DeliveryMan-1.2.1.jar/deliveryman.DeliveryMan.<init>(DeliveryMan.kt:57) ~[DeliveryMan-1.2.1.jar:?]
        at DeliveryMan-1.2.1.jar/deliveryman.bootstrap.DeliveryManPlugin.onLoad(DeliveryManPlugin.java:54) ~[DeliveryMan-1.2.1.jar:?]
        ... 9 more
Caused by: java.lang.IncompatibleClassChangeError: Method 'org.bukkit.Sound[] org.bukkit.Sound.values()' must be InterfaceMethodref constant
        at DeliveryMan-1.2.1.jar/deliveryman.libs.xseries.XSound$Data.<clinit>(XSound.java:2180) ~[DeliveryMan-1.2.1.jar:?]
        at DeliveryMan-1.2.1.jar/deliveryman.libs.xseries.XSound.<init>(XSound.java:1766) ~[DeliveryMan-1.2.1.jar:?]
        at DeliveryMan-1.2.1.jar/deliveryman.libs.xseries.XSound.<clinit>(XSound.java:63) ~[DeliveryMan-1.2.1.jar:?]
        at DeliveryMan-1.2.1.jar/deliveryman.reward.RewardSounds.<init>(RewardSounds.kt:6) ~[DeliveryMan-1.2.1.jar:?]
        at DeliveryMan-1.2.1.jar/deliveryman.reward.RewardSounds.<init>(RewardSounds.kt) ~[DeliveryMan-1.2.1.jar:?]
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at com.google.gson.internal.ConstructorConstructor$9.construct(ConstructorConstructor.java:262) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.createAccumulator(ReflectiveTypeAdapterFactory.java:427) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:383) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:186) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:144) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1329) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1300) ~[gson-2.10.1.jar:?]
        at DeliveryMan-1.2.1.jar/deliveryman.config.MappedConfiguration.getAs(MappedConfiguration.kt:93) ~[DeliveryMan-1.2.1.jar:?]
        at DeliveryMan-1.2.1.jar/deliveryman.config.PluginSettings.<init>(PluginSettings.kt:10) ~[DeliveryMan-1.2.1.jar:?]
        at DeliveryMan-1.2.1.jar/deliveryman.config.PluginSettings.<init>(PluginSettings.kt) ~[DeliveryMan-1.2.1.jar:?]
        at DeliveryMan-1.2.1.jar/deliveryman.config.PluginSettings$Companion.reload(PluginSettings.kt:22) ~[DeliveryMan-1.2.1.jar:?]
        at DeliveryMan-1.2.1.jar/deliveryman.DeliveryMan.<init>(DeliveryMan.kt:57) ~[DeliveryMan-1.2.1.jar:?]
        at DeliveryMan-1.2.1.jar/deliveryman.bootstrap.DeliveryManPlugin.onLoad(DeliveryManPlugin.java:54) ~[DeliveryMan-1.2.1.jar:?]
        ... 9 more

**Comment by CryptoMorin** [comment]
I'm just going to highlight the relevant error.
```hs
Caused by: java.lang.IncompatibleClassChangeError: Method 'org.bukkit.Sound[] org.bukkit.Sound.values()' must be InterfaceMethodref constant
  at DeliveryMan-1.2.1.jar/deliveryman.libs.xseries.XSound$Data.(XSound.java:2180) ~[DeliveryMan-1.2.1.jar:?]
  at DeliveryMan-1.2.1.jar/deliveryman.libs.xseries.XSound.(XSound.java:1766) ~[DeliveryMan-1.2.1.jar:?]
  at DeliveryMan-1.2.1.jar/deliveryman.libs.xseries.XSound.(XSound.java:63) ~[DeliveryMan-1.2.1.jar:?]
```

**Comment by ImYenil** [comment]
> I'm just going to highlight the relevant error.

I get this error even though I built with version 1.16.5

**Comment by CryptoMorin** [comment]
They don't seem to have published this change into their maven repo. I'll fix it once they do that.

**Comment by ImYenil** [comment]
> They don't seem to have published this change into their maven repo. I'll fix it once they do that.

thanks for update but Maven doesn't appear to be working at the moment

**Comment by CryptoMorin** [comment]
> > They don't seem to have published this change into their maven repo. I'll fix it once they do that.
> 
> thanks for update but Maven doesn't appear to be working at the moment

What do you mean by that?

**Comment by ImYenil** [comment]
> > > They don't seem to have published this change into their maven repo. I'll fix it once they do that.
> > 
> > 
> > thanks for update but Maven doesn't appear to be working at the moment
> 
> What do you mean by that?

![image](https://github.com/user-attachments/assets/e6ae76fc-cbb9-4f22-a0d4-bcb2375f5da3)

**Comment by ImYenil** [comment]
This update is currently required. Because there are issues with other plugins as well.
