### ISSUE TITLE
[XMaterial] - A NullPointerException occurs when using the BLACK_DYE material in versions below 1.12.

### ISSUE THREAD

**Issue by ImYenil** [CryptoMorin/XSeries#313]
A NullPointerException occurs when using the DYE material in versions below 1.12.

Console Log
[16:18:12 WARN]: java.lang.NullPointerException
[16:18:12 WARN]:        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:94)
[16:18:12 WARN]:        at com.lielamar.armsrace.managers.ShopManager.getItem(ShopManager.java:71)
[16:18:12 WARN]:        at com.lielamar.armsrace.managers.ShopManager.setup(ShopManager.java:45)
[16:18:12 WARN]:        at com.lielamar.armsrace.managers.ShopManager.<init>(ShopManager.java:31)
[16:18:12 WARN]:        at com.lielamar.armsrace.Main.registerManagers(Main.java:94)
[16:18:12 WARN]:        at com.lielamar.armsrace.Main.onEnable(Main.java:65)
[16:18:12 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[16:18:12 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[16:18:12 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[16:18:12 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[16:18:12 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[16:18:12 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
[16:18:12 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
[16:18:12 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[16:18:12 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
[16:18:12 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[16:18:12 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)

	private CustomItem getItem(String shop, String id) {
		if (!(boolean) config.get("shops." + shop + ".data." + id + ".enabled")) return null; // Don't add disabed items

		// Basic data (Material, quantity, name, lore)
		XMaterial material = XMaterial.valueOf((String) config.get("shops." + shop + ".data." + id + ".material"));
		int quantity = (int) config.get("shops." + shop + ".data." + id + ".quantity");
		String name = ChatColor.translateAlternateColorCodes('&', (String) config.get("shops." + shop + ".data." + id + ".name"));
		List<String> lore = new ArrayList<>();
		for (String s : config.getStringList("shops." + shop + ".data." + id + ".lore"))
			lore.add(ChatColor.translateAlternateColorCodes('&', s));

		System.out.print(material.parseMaterial());
		ItemStack item = new ItemStack(material.parseMaterial(), quantity, material.getData());
		ItemMeta meta = item.getItemMeta();
		meta.setDisplayName(name);
		meta.setLore(lore);
		meta.addItemFlags(ItemFlag.HIDE_ATTRIBUTES);
		meta.addItemFlags(ItemFlag.HIDE_DESTROYS);
		meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
		meta.addItemFlags(ItemFlag.HIDE_PLACED_ON);
		meta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
		item.setItemMeta(meta);

            12:
                enabled: true
                material: BLACK_DYE
                quantity: 1
                name: "&eBlack Mark"
                lore:
                    - ""
                    - "&7Click to buy the"
                    - "&eBlack Mark &7kill effect"
                    - ""
                    - "&7A kill effect of a Black Mark"
                    - "&7when you shoot a projectile"
                    - ""
                    - "&7Price: &e%price%"
                price: 1750
                killeffect: BLACK_MARK

**Comment by CryptoMorin** [comment]
You're not supposed to use `XMaterialparseMaterial()` if your goal is to create an ItemStack. You should use `XMaterial.parseItem()` and never use the getData() method.

**Comment by ImYenil** [comment]
> You're not supposed to use `XMaterial.parseMaterial()` if your goal is to create an ItemStack. You should use `XMaterial.parseItem()` and never use the getData() method.
I changed the code and I still get the same error
[15:04:09 WARN]: java.lang.NullPointerException
[15:04:09 WARN]:        at com.lielamar.armsrace.managers.ShopManager.getItem(ShopManager.java:71)
[15:04:09 WARN]:        at com.lielamar.armsrace.managers.ShopManager.setup(ShopManager.java:45)
[15:04:09 WARN]:        at com.lielamar.armsrace.managers.ShopManager.<init>(ShopManager.java:31)
[15:04:09 WARN]:        at com.lielamar.armsrace.Main.onEnable(Main.java:67)
[15:04:09 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[15:04:09 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[15:04:09 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[15:04:09 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[15:04:09 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[15:04:09 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:769)
[15:04:09 WARN]:        at org.bukkit.Bukkit.reload(Bukkit.java:556)
[15:04:09 WARN]:        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25)
[15:04:09 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146)
[15:04:09 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
[15:04:09 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:629)
[15:04:09 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:416)
[15:04:09 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:379)
[15:04:09 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[15:04:09 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[15:04:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)

		ItemStack item = material.parseItem();
		ItemMeta meta = item.getItemMeta();
		item.setAmount(quantity);
		meta.setDisplayName(name);
		meta.setLore(lore);
		meta.addItemFlags(ItemFlag.HIDE_ATTRIBUTES);
		meta.addItemFlags(ItemFlag.HIDE_DESTROYS);
		meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
		meta.addItemFlags(ItemFlag.HIDE_PLACED_ON);
		meta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
		item.setItemMeta(meta);

**Comment by CryptoMorin** [comment]
How am I supposed to know what that error line refers to? I don't have your entire code to know that. Anyways, I'm assuming it's referring to `item` variable being null in this case.
I'm unable to reproduce this issue with the following code:
```java
XMaterial.matchXMaterial("DYE").parseItem();
```

When printed, this gives "Brown Dye" and not null.
`CraftBukkit version git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)`
