### ISSUE TITLE
[XSound] java.lang.IllegalArgumentException: Unknown standard bukkit form

### ISSUE THREAD

**Issue by UnDeadlyDev** [CryptoMorin/XSeries#314]
java.lang.IllegalArgumentException: Unknown standard bukkit form: ENTITY_GOAT_SCREAMING_HORN_BREAK named ENTITY_GOAT_SCREAMING_HORN_BREAK 

XSound 1.21.1

**Comment by CryptoMorin** [comment]
You need to give me the full error...

**Comment by UnDeadlyDev** [comment]
> You need to give me the full error...

This is sent when you get the sounds


[16:17:27 ERROR]: Could not pass event PlayerMoveEvent to UHubCore v1.4.2
java.lang.IllegalArgumentException: Unknown standard bukkit form: ENTITY_GOAT_SCREAMING_HORN_BREAK named ENTITY_GOAT_SCREAMING_HORN_BREAK
        at UHubCore-1.4.2.jar/libraries.xseries.base.XRegistry.std(XRegistry.java:302) ~[UHubCore-1.4.2.jar:?]
        at UHubCore-1.4.2.jar/libraries.xseries.base.XRegistry.std(XRegistry.java:288) ~[UHubCore-1.4.2.jar:?]
        at UHubCore-1.4.2.jar/libraries.xseries.base.XRegistry.pullSystemValues(XRegistry.java:123) ~[UHubCore-1.4.2.jar:?]
        at UHubCore-1.4.2.jar/libraries.xseries.base.XRegistry.pullValues(XRegistry.java:86) ~[UHubCore-1.4.2.jar:?]
        at UHubCore-1.4.2.jar/libraries.xseries.base.XRegistry.getByName(XRegistry.java:219) ~[UHubCore-1.4.2.jar:?]
        at UHubCore-1.4.2.jar/libraries.xseries.XSound.matchXSound(XSound.java:1802) ~[UHubCore-1.4.2.jar:?]
        at UHubCore-1.4.2.jar/com.undeadlydev.UHubCore.modules.launchPads.listeners.launchPadsListeners.onPlayerMove(launchPadsListeners.java:74) ~[UHubCore-1.4.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor41.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-132-b48403b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1561) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:34) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Rot.handle(ServerboundMovePlayerPacket.java:139) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1586) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by UnDeadlyDev** [comment]
> You need to give me the full error...

This is sent when you get the sounds

[16:17:27 ERROR]: Could not pass event PlayerMoveEvent to UHubCore v1.4.2
java.lang.IllegalArgumentException: Unknown standard bukkit form: ENTITY_GOAT_SCREAMING_HORN_BREAK named ENTITY_GOAT_SCREAMING_HORN_BREAK
at UHubCore-1.4.2.jar/libraries.xseries.base.XRegistry.std(XRegistry.java:302) ~[UHubCore-1.4.2.jar:?]
at UHubCore-1.4.2.jar/libraries.xseries.base.XRegistry.std(XRegistry.java:288) ~[UHubCore-1.4.2.jar:?]
at UHubCore-1.4.2.jar/libraries.xseries.base.XRegistry.pullSystemValues(XRegistry.java:123) ~[UHubCore-1.4.2.jar:?]
at UHubCore-1.4.2.jar/libraries.xseries.base.XRegistry.pullValues(XRegistry.java:86) ~[UHubCore-1.4.2.jar:?]
at UHubCore-1.4.2.jar/libraries.xseries.base.XRegistry.getByName(XRegistry.java:219) ~[UHubCore-1.4.2.jar:?]
at UHubCore-1.4.2.jar/libraries.xseries.XSound.matchXSound(XSound.java:1802) ~[UHubCore-1.4.2.jar:?]
at UHubCore-1.4.2.jar/com.undeadlydev.UHubCore.modules.launchPads.listeners.launchPadsListeners.onPlayerMove(launchPadsListeners.java:74) ~[UHubCore-1.4.2.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor41.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-132-b48403b]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1561) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:34) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Rot.handle(ServerboundMovePlayerPacket.java:139) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1586) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by CryptoMorin** [comment]
Also from #316

```hs
java.lang.IllegalArgumentException: Unknown standard bukkit form: ITEM_SWEET_BERRIES_PICK_FROM_BUSH named ITEM_SWEET_BERRIES_PICK_FROM_BUSH
	at deliveryman.libs.xseries.base.XRegistry.std(XRegistry.java:302) ~[?:?]
	at deliveryman.libs.xseries.base.XRegistry.std(XRegistry.java:288) ~[?:?]
```
