### ISSUE TITLE
java.lang.IllegalArgumentException: Unknown standard bukkit form: ITEM_SWEET_BERRIES_PICK_FROM_BUSH named ITEM_SWEET_BERRIES_PICK_FROM_BUSH

### ISSUE THREAD

**Issue by Revxrsal** [CryptoMorin/XSeries#316]
Hello o/

**Description**
A bug occurs when loading the XSound class:

```
java.lang.IllegalArgumentException: Unknown standard bukkit form: ITEM_SWEET_BERRIES_PICK_FROM_BUSH named ITEM_SWEET_BERRIES_PICK_FROM_BUSH
	at deliveryman.libs.xseries.base.XRegistry.std(XRegistry.java:302) ~[?:?]
	at deliveryman.libs.xseries.base.XRegistry.std(XRegistry.java:288) ~[?:?]
	at deliveryman.libs.xseries.base.XRegistry.pullSystemValues(XRegistry.java:123) ~[?:?]
	at deliveryman.libs.xseries.base.XRegistry.pullValues(XRegistry.java:86) ~[?:?]
	at deliveryman.libs.xseries.base.XRegistry.getByName(XRegistry.java:219) ~[?:?]
	at deliveryman.libs.xseries.XSound.matchXSound(XSound.java:1802) ~[?:?]
	at deliveryman.gson.XSeriesTypeAdapterFactory.mapping$lambda$0(XSeriesTypeAdapterFactory.kt:17) ~[?:?]
	at deliveryman.gson.XSeriesTypeAdapterFactory$create$1.read(XSeriesTypeAdapterFactory.kt:41) ~[?:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[patched_1.16.5.jar:git-Paper-790]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[patched_1.16.5.jar:git-Paper-790]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[patched_1.16.5.jar:git-Paper-790]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[patched_1.16.5.jar:git-Paper-790]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[patched_1.16.5.jar:git-Paper-790]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187) ~[patched_1.16.5.jar:git-Paper-790]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[patched_1.16.5.jar:git-Paper-790]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[patched_1.16.5.jar:git-Paper-790]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[patched_1.16.5.jar:git-Paper-790]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[patched_1.16.5.jar:git-Paper-790]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[patched_1.16.5.jar:git-Paper-790]
	at deliveryman.config.MappedConfiguration.getAs(MappedConfiguration.kt:93) ~[?:?]
	at deliveryman.config.PluginSettings.<init>(PluginSettings.kt:10) ~[?:?]
	at deliveryman.config.PluginSettings.<init>(PluginSettings.kt) ~[?:?]
	at deliveryman.config.PluginSettings$Companion.reload(PluginSettings.kt:22) ~[?:?]
	at deliveryman.DeliveryMan.<init>(DeliveryMan.kt:57) ~[?:?]
	at deliveryman.bootstrap.DeliveryManPlugin.onLoad(DeliveryManPlugin.java:54) ~[?:?]
	... 5 more
```

**Version**
Minecraft 1.16.5

**Comment by CryptoMorin** [comment]
I'm going to move this to #314 and mark this as a duplicate.
