### ISSUE TITLE
[XMaterial] - matchXMaterial(ItemStack) not working for doors

### ISSUE THREAD

**Issue by SkytAsul** [CryptoMorin/XSeries#42]
**Description**
On 1.15.2, calling `XMaterial.matchXMaterial(new ItemStack(Material.SPRUCE_DOOR))` throws this exception:
```
[20:54:44 WARN]: Caused by: java.lang.IllegalArgumentException: Unsupported Material: SPRUCE_DOOR (0)
[20:54:44 WARN]:    at fr.skytasul.quests.utils.XMaterial.lambda$matchXMaterial$1(XMaterial.java:1481)
[20:54:44 WARN]:    at java.util.Optional.orElseThrow(Unknown Source)
[20:54:44 WARN]:    at fr.skytasul.quests.utils.XMaterial.matchXMaterial(XMaterial.java:1481)
```
...whereas it should return `XMaterial.SPRUCE_DOOR`.

**Version**
Server version: 1.15.2

**Comment by CryptoMorin** [comment]
I couldn't reproduce it. Make sure you have the latest version.

**Comment by SkytAsul** [comment]
A problem on my end, sorry :/
