### ISSUE TITLE
XMaterial - Unsupported Materials (with and with no bytes)

### ISSUE THREAD

**Issue by officialrarlab** [CryptoMorin/XSeries#45]
**Description**
This has been going on since the 1.16 update and there is no pinpointing. Keep in mind, this happens with all 1.16 materials; if it were to be doors, it would throw an exception regarding no bytes iirc (unfortunately I do not have the stracktrace for this, all I know is that I've witnessed it myself), here comes the SHROOMLIGHT one though:

```
java.lang.IllegalArgumentException: Unsupported Material: SHROOMLIGHT
at com.cryptomorin.xseries.XMaterial.lambda$matchXMaterial$0(XMaterial.java:1390) ~[?:?]
at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_242]
at com.cryptomorin.xseries.XMaterial.matchXMaterial(XMaterial.java:1390) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor31.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-47]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-47]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-47]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-47]
at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:497) ~[patched_1.16.1.jar:git-Paper-47]
at net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:459) ~[patched_1.16.1.jar:git-Paper-47]
at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1449) ~[patched_1.16.1.jar:git-Paper-47]
at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.1.jar:git-Paper-47]
at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.1.jar:git-Paper-47]
at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-47]
at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-47]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-47]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-47]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-47]
at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-47]
at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-47]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-47]
at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-47]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-47]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-47]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

**Version**
Running the latest 1.16 update at these events.

**Comment by CryptoMorin** [comment]
Please use the latest version because right now this is line [1390](https://github.com/CryptoMorin/XSeries/blob/16009138362619aa302f1237410394aa2afd922e/src/main/java/com/cryptomorin/xseries/XMaterial.java#L1390)

**Comment by CryptoMorin** [comment]
I'm closing this since I haven't got any replies for a week.
